### PR TITLE
I have included some lines in README.md

### PR DESCRIPTION
**Pull request by akshay20105**

### CODE REVIEW

**Comment by akshay20105** [comment]
Hello, 
Please review and accept my pull request and Please do not mark it as spam or invalid because i am participating in an Hackathon there is no requirement of merging it please review and please do not mark as invalid or spam.

**Comment by y-martinez** [comment]
This PR is a spam (for Hacktoberfest) , please maintainers mark such as invalid

**Comment by akshay20105** [comment]
> This PR is a spam (for Hacktoberfest) , please maintainers mark such as invalid

Oh okay,
I am gonna close this pull request if u say so.
:( :(

**Comment by y-martinez** [comment]
> > This PR is a spam (for Hacktoberfest) , please maintainers mark such as invalid
> 
> Oh okay,
> I am gonna close this pull request if u say so.
> :( :(

Sir the Hacktoberfest was created to promote the contribution to open source, but you should do better PR because probably you will disqualify

**Pull request closed without merging**
